baseURL = "https://ljohnson-adm.com/"
locale = "en-us"
title = "Landon Johnson | For the Love of Technology"
theme = "PaperMod"

[params]
  description = "Notes on Windows Server, Linux, M365, Azure, networking, and homelab projects."
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true
  ShowToc = true

[[menu.main]]
  name = "Posts"
  url = "/posts/"
  weight = 1

[[menu.main]]
  name = "Projects"
  url = "/projects/"
  weight = 2

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 3

[taxonomies]
  tag = "tags"
  category = "categories"
